## chap 1.3.2

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
x = 250
y = 10
x + y

260

In [3]:
x = np.uint8([250])

In [4]:
x

array([250], dtype=uint8)

In [5]:
x + y

array([4], dtype=uint8)

In [6]:
cv2.add(x, y)

array([[255]], dtype=uint8)

In [7]:
img1 = cv2.imread('test1.png')
img2 = cv2.imread('test2.png')

In [ ]:
w = 0.5
dst = cv2.addWeighted(img1,w,img2,1-w,0)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroytAllWindows()

In [ ]:
def nothing(x):
    pass

In [ ]:
w = 0.5
cv2.namedWindow('image')
cv2.createTrackbar('weight', 'image',0,255,nothing)

while True:
    if cv2.waitKey(2) & 0xFF == 27:
        break
    weight = cv2.getTrackbarPos('weight', 'image')    
    dst = cv2.addWeighted(img1,weight/255,img2,1-weight/255,0)
    cv2.imshow('image',dst)

cv2.destroyAllWindows()